//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemeshkanОТКПривет
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemeshkanOTKprogEntities1 : DbContext
    {
        private static DemeshkanOTKprogEntities1 _context;
        public DemeshkanOTKprogEntities1()
            : base("name=DemeshkanOTKprogEntities1")
        {
        }
    
        public static DemeshkanOTKprogEntities1 GetContext()
        {
            if (_context == null)
                _context = new DemeshkanOTKprogEntities1();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
